api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import SpaceViewSet, EmployeeViewSet, ReserveViewSet


# app_name = 'api'

router = DefaultRouter()

router.register(r'spaces', SpaceViewSet)
router.register(r'employees', EmployeeViewSet)
router.register(r'reserves', ReserveViewSet)

urlpatterns = router.urls

parking_spaces/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.schemas import get_schema_view 
from rest_framework.documentation import include_docs_urls


schema_view = get_schema_view(title='Parking Spaces API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spaces.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('docs/', include_docs_urls(title='Parking Spaces')),
    path('schema/', schema_view),
]

spaces/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from .views import SpaceList, SpaceDetail, SpaceCreate, SpaceUpdate, SpaceDelete
from .views import ReserveList, ReserveDetail, ReserveCreate, ReserveUpdate, ReserveDelete


app_name = 'spaces'

urlpatterns = [
    path('', SpaceList.as_view(), name='spaces'),
    path('<int:pk>/', SpaceDetail.as_view(), name='space'),
    path('create/', SpaceCreate.as_view(), name='space_create'),
    path('<int:pk>/update/', SpaceUpdate.as_view(), name='space_update'),
    path('<int:pk>/delete/', SpaceDelete.as_view(), name='space_delete'),
    path('login/', LoginView.as_view(template_name='spaces/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name = 'spaces/logout.html'), name='logout'),
    path('reserve/', ReserveList.as_view(), name='reserve_list'),
    path('reserve/<int:pk>/', ReserveDetail.as_view(), name='reserve_detail'),
    path('reserve/create/', ReserveCreate.as_view(), name='reserve_create'),
    path('reserve/<int:pk>/update/', ReserveUpdate.as_view(), name='reserve_update'),
    path('reserve/<int:pk>/delete/', ReserveDelete.as_view(), name='reserve_delete'),
]

api/models.py
from django.db import models

# Create your models here.

spaces/models.py
from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    ROLE_CHOICES = (
        ('MANAGER', 'manager'),
        ('EMPLOYEE', 'employee')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='employee')
    
    def __str__(self):
        return f'{self.user.username} {self.role}'


class Space(models.Model):
    STATUS_CHOICES = (
        ('BOOKED', 'booked'),
        ('RESERVED', 'reserved'),
        ('RELEASED', 'released')
    )
    
    title = models.CharField(max_length = 128)
    status = models.CharField(max_length = 64, choices=STATUS_CHOICES, default='released')
    
    def __str__(self):
        return f'{self.title}'
    



class Reserve(models.Model):
    space = models.ForeignKey(Space, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    start_time = models.DateTimeField()
    duration = models.IntegerField(default=1)
    
    def __str__(self):
        return f'{self.space} at {self.start_time} by {self.employee.user.username}'
    
    
    

spaces/forms.py
from django.forms import ModelForm

from .models import Space, Reserve


class SpaceForm(ModelForm):
    class Meta:
        model = Space
        fields = '__all__'
        

class ReserveForm(ModelForm):
    class Meta:
        model = Reserve
        fields = '__all__'

api/views.py
from django.shortcuts import render
from rest_framework import viewsets

from spaces.models import Space, Employee, Reserve
from .serializers import SpaceSerializer, EmployeeSerializer, ReserveSerializer


class SpaceViewSet(viewsets.ModelViewSet):
    serializer_class = SpaceSerializer
    queryset = Space.objects.all()
    

class EmployeeViewSet(viewsets.ModelViewSet):
    serializer_class = EmployeeSerializer
    queryset = Employee.objects.all()
    

class ReserveViewSet(viewsets.ModelViewSet):
    serializer_class = ReserveSerializer
    queryset = Reserve.objects.all()
    

spaces/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import PermissionRequiredMixin

from .models import Space, Reserve
from .forms import SpaceForm, ReserveForm


class SpaceList(generic.ListView):
    model = Space
    template_name = 'spaces/list.html'
    context_object_name = 'spaces'
    queryset = Space.objects.all()
    
    
class SpaceDetail(generic.DetailView):
    model = Space
    template_name = 'spaces/detail.html'
    form_class = SpaceForm
    # context_object_name = 'space'
    # queryset = Space.objects.all()


class SpaceCreate(PermissionRequiredMixin, generic.CreateView):
    permission_required = ('spaces.add_space',)
    template_name = 'spaces/space_create.html'
    form_class = SpaceForm
    success_url = '/'
    

class SpaceUpdate(PermissionRequiredMixin, generic.UpdateView):
    permission_required = ('spaces.change_space',)
    template_name = 'spaces/space_create.html'
    form_class = SpaceForm
    success_url = '/'
    
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Space.objects.get(pk=id)
    

class SpaceDelete(PermissionRequiredMixin, generic.DeleteView):
    permission_required = ('spaces.delete_space',)
    template_name = 'spaces/space_delete.html'
    queryset = Space.objects.all()
    success_url = '/'
    

# Reserve CRUD
class ReserveList(generic.ListView):
    model = Reserve
    template_name = 'spaces/reserve_list.html'
    context_object_name = 'reserves'
    queryset = Reserve.objects.all()
    

class ReserveDetail(generic.DetailView):
    model = Reserve
    template_name = 'spaces/reserve_detail.html'
    form_class = ReserveForm
    context_object_name = 'reserve'
    

class ReserveCreate(PermissionRequiredMixin, generic.CreateView):
    permission_required = ('spaces.add_reserve',)
    template_name = 'spaces/reserve_create.html'
    form_class = ReserveForm
    success_url = '/reserve/'
    

class ReserveUpdate(PermissionRequiredMixin, generic.CreateView):
    permission_required = ('spaces.change_reserve',)
    template_name = 'spaces/reserve_create.html'
    form_class = ReserveForm
    success_url = '/reserve/'
    
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Reserve.objects.get(pk=id)
    

class ReserveDelete(PermissionRequiredMixin, generic.DeleteView):
    permission_required = ('spaces.delete_reserve',)
    template_name = 'spaces/reserve_delete.html'
    queryset = Reserve.objects.all()
    success_url = '/reserve/'
    

spaces/templates/spaces/detail.html
{% extends 'main.html' %}

{% block title %}
    {{ space.title }}
{% endblock title %}

{% block content %}
    <a href="{% url 'spaces:space_update' space.pk %}">Изменить</a> | 
    <a href="{% url 'spaces:space_delete' space.pk %}">Удалить</a> | 
    <a href="/">Назад</a>
    <h2>Парковочное место: {{ space.title }}</h2>
    <p>Статус: {{ space.status }}</p>
    <a href="{% url 'spaces:reserve_list' %}"><h3>История парковок</h3></a>
{% endblock content %}

spaces/templates/spaces/list.html
{% extends 'main.html' %}

{% block title %}
    Parking Spaces
{% endblock title %}

{% block content %}
    <p><a href="{% url 'spaces:space_create' %}">Добавить новое парковочное место</a></p>
    <h3>Парковочные места</h3>
    {% if spaces %}
        <form method="GET" action="{% url 'spaces:reserve_create' %}">
            <button type="submit"><h3>Бронировать</h3></button>
        </form>
        {% for space in spaces %}
            <a href="{% url 'spaces:space' space.pk %}">
                <div>
                    <h3>{{ space.title }}</h3>
                    <p>Статус: {{ space.status }}</p
                </div>
            </a>
        {% endfor %}
    {% else %}
        Нет парковочных мест!
    {% endif %}
{% endblock content %}

spaces/templates/spaces/login.html
{% extends 'main.html' %}

{% block title %}
    Login
{% endblock title %}

{% block content %}
    <h2> Войти в систему </h2>
    <form method="post" action="{% url 'spaces:login' %}">
        {% csrf_token %}
            <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="Войти">
    </form>
    <button> <a href="/"> Назад </a></button>
{% endblock %}

spaces/templates/spaces/logout.html
{% extends 'main.html' %}

{% block content %}
    <h2> Вы вышли из системы. </h2>

{% endblock %}

spaces/templates/spaces/reserve_create.html
{% extends 'main.html' %}

{% block title %}New Booking{% endblock title %}
 
{% block content %}
    <a href="/reserve/">Назад</a>
    <h3>Информация о бронировании парковочного места</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }} 
        <input type="submit" value="Сохранить">
    </form>
{% endblock content %}

spaces/templates/spaces/reserve_delete.html
{% extends 'main.html' %}

{% block title %}
    {{ reserve.space }} at {{ reserve.start_time }}
{% endblock title %}

{% block content %}
    <h2>Вы действительно хотите удалить данные о бронировании?</h2>
    <h3>Парковочное место: {{ reserve.space.title }}</h3>
    <h4>Сотрудник: {{ reserve.employee }}</h4>
    <p>Дата и время создания: {{ reserve.created }}</p>
    <p>Дата и время начала: {{ reserve.start_time }}</p>
    <p>Продолжительность: {{ reserve.duration }} часов.</p>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Удалить">
    </form>
{% endblock content %}

spaces/templates/spaces/reserve_detail.html
{% extends 'main.html' %}

{% block title %}
    {{ reserve.space }} at {{ reserve.start_time }}
{% endblock title %}

{% block content %}
    <a href="{% url 'spaces:reserve_update' reserve.pk %}">Изменить</a> | 
    <a href="{% url 'spaces:reserve_delete' reserve.pk %}">Удалить</a> | 
    <a href="/reserve/">Назад</a>
    <h3>Парковочное место: {{ reserve.space.title }}</h3>
    <h4>Сотрудник: {{ reserve.employee }}</h4>
    <p>Дата и время создания: {{ reserve.created }}</p>
    <p>Дата и время начала: {{ reserve.start_time }}</p>
    <p>Продолжительность: {{ reserve.duration }} часов.</p>
    
{% endblock content %}

spaces/templates/spaces/reserve_list.html
{% extends 'main.html' %}

{% block title %}
    Reserves
{% endblock title %}

{% block content %}
    <p>
        <a href="{% url 'spaces:reserve_create' %}">Добавить</a> | 
        <a href="/">Назад</a>
    </p>
    <h2>Список бронирований</h2>
    {% if reserves %}
        <!-- <form method="GET" action="{% url 'spaces:reserve_create' %}">
            <button type="submit"><h3>Бронировать</h3></button>
        </form> -->
        {% for reserve in reserves %}
            <div>
                <h3>Парковочное место: {{ reserve.space.title }}</h3>
                <!-- <h4>Сотрудник: {{ reserve.employee }}</h4> -->
                <!-- <p>Дата и время создания: {{ reserve.created }}</p> -->
                <p>Дата и время начала: {{ reserve.start_time }}</p>
                <p>Продолжительность: {{ reserve.duration }} ч.</p>
                <a href="{% url 'spaces:reserve_detail' reserve.pk %}">Подробнее</a>
            </div>
            
        {% endfor %}
    {% else %}
        Бронирования не было!
    {% endif %}
{% endblock content %}

spaces/templates/spaces/space_create.html
{% extends 'main.html' %}

{% block title %} New Parking {% endblock title %}
 
{% block content %}
    <h3>Добавление парковочного места</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }} 
        <input type="submit" value="Сохранить">
    </form>
{% endblock content %}

spaces/templates/spaces/space_delete.html
{% extends 'main.html' %}

{% block title %}
    {{ space.title }}
{% endblock title %}

{% block content %}
    <h2>Вы действительно хотите удалить данное парковочное место?</h2>
    <h3>{{ space.title }}</h3>
    <!-- {{ space.created | date:'d M Y' }} -->
    <form method="POST">
    {% csrf_token %}
    <input type="submit" value="Удалить">
    </form>
{% endblock content %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} - Fregat Office Center</title>
</head>
<body>
    <header>
        <h1>Parking Space "Fregat Office Center"</h1>
        <a href="{% url 'spaces:login' %}">Войти</a> | 
        <a href="{% url 'spaces:logout' %}">Выйти</a>
        <hr>
    </header>
    {% block content %}
    {% endblock content %}
    <footer>
        <hr>
        <h2>Copyright Fregat Office Center</h2>
    </footer>
</body>
</html>